Slug atualizado
obg-lab/jornada-site pull request #5
Opened 2020-11-14 15:12 UTC by Guigalaverna

O slug desse desafio estava com erros de ortografia

2020-11-16 12:43 UTC, egermano commented
Tem coisas muito legais ai, mas tem bastante coisa que a gente pode melhorar. Como por exemplo o CSS, nesse projeto estamos usando o SASS e você não usou nenhum recurso dele.

Eu vou comentar com o links das documentações em cada parte.

2020-11-16 12:53 UTC, egermano requested changes

2020-11-16 12:53 UTC, egermano commented on src/components/difficulty.js
> +  if (difficulty === "iniciante") {
Acho que a melhor opção aqui é usar switch case e não if, else if e else. Imagina um dia se tivermos mais 3 niveis de dificuldades como vai ser a muanutenção desse código.

2020-11-16 12:53 UTC, egermano commented on src/components/difficulty.js
> +      <div className='difficulty-easy-container'>
Outra coisa, acho que a gente conseguiria fazer uma leogica melhor aqui, todos os HTML parecem ser os mesmos e o que muda é a classe do elemento, não daria para colocar essas condições para escrever as classes apenas?

2020-11-16 12:53 UTC, egermano commented on src/components/signupForm.js
> +      <h2 className='sign-up-title'>Venha fazer parte da Jornada</h2>
Os nomes de classes estão certos, mas aqui estamos usando o paradigma chamado BEM CSS: http://getbem.com/introduction/

2020-11-16 12:53 UTC, egermano commented on src/markdown/binario para decimal.md
> +difficulty: "intermediario"
Gostei bastante dessa idéia dos autores e nivel de dificuldades.

2020-11-16 12:53 UTC, egermano commented on src/markdown/gerador-de-border-radius.md
> +difficulty: 'avancado'
Eu acho que esse desafio é intermediário.

2020-11-16 12:53 UTC, egermano commented on src/pages/index.js
> +          <h2 className='about-title'>Sobre o projeto</h2>
A mesma coisa sobre o BEM, da uma olhada na documentação e ver se não tem um esquema de escrever o nome diferente.

2020-11-16 12:53 UTC, egermano commented on src/style/components/difficulty.scss
> +  background-color: #10ed4f;
O ideal é que essas corres fossem variaveis no SASS assim a gente consegui por exemplo criar uma versão dark e light. https://sass-lang.com/documentation/variables

2020-11-16 12:53 UTC, egermano commented on src/style/components/difficulty.scss
> +  color: white;
existe uma variavel para white. Evista usar essas cores padrão do CSS pq acaba que a gente perde flexibilidade no codigo.

2020-11-16 12:53 UTC, egermano commented on src/style/components/difficulty.scss
> +
Outra coisa sobre boa pratica, isso é uma opinião pessoal minha.

Evita deixar espaços desnecessarios nas declarações de atributos aqui e mantenha todos os atributos em ordem alfabética.

2020-11-16 12:53 UTC, egermano commented on src/style/layout.scss
> +.blog-post-container .blog-post-title {
O SASS permite que você aninhe declarações para ficar mais facil de ler e de dar manutenção: https://www.w3schools.com/sass/sass_nesting.asp

2021-03-20 15:04 UTC, closed without merging

2021-03-20 15:05 UTC, Guigalaverna commented
Reformulando o código... 👍