Componente Level Indicator
obg-lab/jornada-site pull request #7
Opened 2021-03-20 15:19 UTC by Guigalaverna

Eu refiz o componente Level Indicator usando classes do SCSS para determinar qual seria a cor do componente e a lógica foi refeita, acredito que tenha resolvido o problema 👍

2021-03-23 13:39 UTC, egermano requested changes
Ta no caminho... São pequenos ajustes de texto na maioria.

2021-03-23 13:39 UTC, egermano commented on src/markdown/calculadora.md
> +## Histórias de usuários
A gente ta usando esse titulo como `Funcionalidades`. Esses termos como histórioa de usuários pode ser muito avançado para algumas pessoas.

2021-03-23 13:39 UTC, egermano commented on src/markdown/calculadora.md
> +- [Calculadora (Wikipedia)] (https://en.wikipedia.org/wiki/Calculator)
Seria legal colocar os links em pt-BR se tiver.

2021-03-23 13:39 UTC, egermano commented on src/markdown/dolar-para-cents.md
> +## Histórias de usuários
O mesmo lance desse título o ideal seria: `Funcionalidades`

2021-03-23 13:39 UTC, egermano commented on src/markdown/dolar-para-cents.md
> +slug: '/desafios/dolar-para-cents'
Esse desafio está muito parecido com um outro que eu coloquei de converter valores em moedas. Me diz o que vc acha, é redundante? Eu acho que me inspirei na mesma fonte.

2021-03-23 13:39 UTC, egermano commented on src/markdown/gerador-de-lorem-ipsun.md
> +## Histórias de usuários
O mesmo lance do título, o ideal é : `Funcionalidades`

2021-03-23 13:39 UTC, egermano commented on src/markdown/calculadora.md
> +- O usuário pode ver uma tela mostrando o número atual inserido ou o resultado da última operação.
Usar palavras como `usuário` querendo ou não define o genero da pessoal que você imagina que esteja usando. É um longo histórico na tecnologia de uso de palavras como essa. Acho que fica melhor usar palavras sem genero como `pessoa`, ou `Quem usa pode ver ...`.

2021-03-23 13:39 UTC, egermano commented on src/markdown/calculadora.md
> +- O usuário pode ver um painel de entrada contendo botões para os dígitos 0-9, operações - '+', '-', '/' e '=', um botão 'C' (para limpar) e um 'AC' botão (para limpar tudo).
O mesmo lance de `usuário`

2021-03-23 13:39 UTC, egermano commented on src/markdown/calculadora.md
> +- O usuário pode inserir números como sequências de até 8 dígitos clicando em dígitos no teclado de entrada. A entrada de qualquer dígito superior a 8 será ignorada.
O mesmo lance de `usuário`

2021-03-23 13:39 UTC, egermano commented on src/markdown/calculadora.md
> +- O usuário pode clicar em um botão de operação para exibir o resultado dessa operação em: * o resultado da operação anterior e o último número inserido OU * os dois últimos números inseridos OU * o
O mesmo lance de `usuário`

2021-03-23 13:39 UTC, egermano commented on src/markdown/calculadora.md
> +- O usuário pode clicar no botão 'C' para limpar o último número ou o último Operação. Se a última entrada do usuário foi uma operação, o display será atualizado para o valor que o precedeu.
O mesmo lance de `usuário`

2021-03-23 13:39 UTC, egermano commented on src/markdown/calculadora.md
> +- O usuário pode clicar no botão 'AC' para limpar todas as áreas de trabalho internas e para definir a exibição para 0.
O mesmo lance de `usuário`

2021-03-23 13:39 UTC, egermano commented on src/markdown/calculadora.md
> +- O usuário pode ver 'ERR' exibido se qualquer operação exceder o Máximo de 8 dígitos.
O mesmo lance de `usuário`

2021-03-23 13:39 UTC, egermano commented on src/markdown/dolar-para-cents.md
> +- O usuário pode inserir um valor em dólares
O mesmo lance de `usuário`

2021-03-23 13:39 UTC, egermano commented on src/markdown/dolar-para-cents.md
> +- O usuário pode ver os centavos totais do valor do dólar convertido
O mesmo lance de `usuário`

2021-03-23 13:39 UTC, egermano commented on src/markdown/gerador-de-lorem-ipsun.md
> +- O usuário pode digitar em um campo de entrada o número de parágrafos de lorem ipsum a serem gerados
O mesmo lance de `usuário`

2021-03-23 13:39 UTC, egermano commented on src/markdown/gerador-de-lorem-ipsun.md
> +- Use pode ver os parágrafos gerados de lorem ipsum e é capaz de copiá-los
Tem um erro de digitação, mas o mesmo lance de `usuário`

2021-03-23 13:39 UTC, egermano commented on src/markdown/gerador-de-lorem-ipsun.md
> +- [lorem-very Cdn] (https://www.jsdelivr.com/package/npm/lorem-ipsum)
Se tiver mais algum link ou recurso que não seja de JS seria otimo pq vc marcou esse desafio como agnostico. Ou você pode falar que o desafio é de Javascript.

2021-03-23 13:39 UTC, egermano commented on src/markdown/timer.md
> +tags: agnostico, matematica
matemática tem acento e agnóstico tmb.

2021-03-23 13:39 UTC, egermano commented on src/markdown/timer.md
> +## Histórias de usuários
O mesmo lance do título, o ideal é : `Funcionalidades`

2021-03-23 13:39 UTC, egermano commented on src/markdown/timer.md
> +- O usuário pode ver uma caixa de entrada de evento contendo um campo de nome de evento, um campo de data, uma hora opcional e um botão 'Iniciar'.
O mesmo lance de usar `usuário`

2021-03-23 13:39 UTC, egermano commented on src/markdown/timer.md
> +
O mesmo lance de usar `usuário`

2021-03-23 13:39 UTC, egermano commented on src/markdown/timer.md
> +- O usuário pode ver uma mensagem de aviso se a data ou hora do evento estiverem incorretas entrou.
O mesmo lance de usar `usuário`

2021-03-23 13:39 UTC, egermano commented on src/markdown/timer.md
> +- O usuário pode ver uma mensagem de aviso se o tempo até a data e hora do evento que foi inserido iria estourar a precisão do cronômetro de contagem regressiva.
O mesmo lance de usar `usuário`

2021-03-23 13:39 UTC, egermano commented on src/markdown/timer.md
> +- O usuário pode clicar no botão 'Iniciar' para ver o início do cronômetro de contagem regressiva exibindo os dias, horas, minutos e segundos até que o evento ocorra.
O mesmo lance de usar `usuário`

2021-03-23 13:39 UTC, egermano commented on src/markdown/timer.md
> +- O usuário pode ver os elementos no cronômetro de contagem regressiva automaticamente decremento. Por exemplo, quando a contagem de segundos restantes chega a 0, o restante a contagem dos minutos di
O mesmo lance de usar `usuário`

2021-03-23 13:39 UTC, egermano commented on src/style/components/_level-indicator.scss
> +
ta sobrando linhas vazias aqui e para mim o ideal de CSS é colocar os atributos em ordem alfabetica, assim fica mais facil de outras pessoas lerem.

2021-03-23 13:39 UTC, egermano commented on src/components/level-indicator.js
> +      { level === "Iniciante" ? (
Ao invez de usar condições em `string` pq vc não usa o level em inteiro?

2021-03-23 13:39 UTC, egermano commented on src/components/level-indicator.js
> +        <span className='levelIndicator-badge levelIndicator-badge-beginner' />
Se você for ver todos os elementos dentro das condições são muito parecidos, pq vc não cria apenas 1 `span` e manipula a classe dele?

2021-03-23 13:39 UTC, egermano commented on src/components/level-indicator.js
> +      <a className='levelIndicator-level'>{ level }</a>
elemento 'a' sem `href`. Ou falta o 'href' ou não deveria ser 'a'.

2021-03-23 13:39 UTC, egermano commented on src/style/components/_level-indicator.scss
> +  background-color: #161616;
para mim o ideal é que essa cor fosse uma variavel, se tiver como faz usando variavel. assim essa cor pode ser reutilizada em outros lugares.

2021-03-23 13:39 UTC, egermano commented on src/markdown/calculadora.md
> +tags: agnostico, matematica
matemática tem acento e agnóstico tmb.

2021-03-23 13:39 UTC, egermano commented on src/markdown/dolar-para-cents.md
> +tags: agnostico, matematica
matemática tem acento. e agnóstico também.

2021-03-24 18:04 UTC, Guigalaverna commented on src/markdown/calculadora.md
> +- [Calculadora (Wikipedia)] (https://en.wikipedia.org/wiki/Calculator)
O link da MDN só encontrei em inglês

2021-03-25 03:09 UTC, closed without merging